baseURL = 'whoami.rezarajan.me/'
languageCode = 'en-us'
title = 'Resume'
theme = 'resume-a4'
disableKinds= ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]

# For GitHub Actions
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Customizations 
[params]
useFontAwesome = true
externalLinkIcon = true
css = ["custom.scss"] # ["print_urls.scss"]

[params.header]
avatar = false # "avatar.jpg"
contact = true
tagline = true
links = true

[params.itemTitle]
useFontAwesome = false
externalLinkIcon = false

[params.experience.roles.role]
show = false

[params.experience.tools]
show = false
title = "Technologies"

[params.education]
useFontAwesome = true
externalLinkIcon = false
location.show = false
details.show = false
namePrimary = true


# Page 1
[[params.pages]]

# Side column

[[params.side]]
feature = "certificates"
title = "Certifications"
#
[[params.side]]
feature = "education"
#
# [[params.side]]
# feature = "awards"
#
[[params.side]]
feature = "skills"
title = "Technical Skills"
widget = "word-list"
style = "compact" # "list", "compact", "title-list"

# [[params.side]]
# feature = "projects"

# [[params.side]]
# feature = "languages"

# Main Section

# [[params.pages.features]]
# feature = "skills"
# title = "Technical Skills"
# widget = "word-list"
# style = "compact" # "list", "compact", "title-list"

[[params.pages.features]]
feature = "experience"
title = "Experience"

# [[params.pages.features]]
# feature = "projects"
# title = "Project Experience"

# [[params.pages.features]]
# feature = "education"
# title = "Education"


# Page 2

## Uncomment this to add the second page
# [[params.pages]]

# [[params.pages.features]]
# feature = "courses"
# title = "Courses"



# Footer
[params.footer]
footnote = "You can print this resume in A4 size or save as pdf."
show = true
credits = false

[[params.footer.links]]
prefix = "Contact me on"
title = "Linkedin"
url = "https://linkedin.com/in/rezarajan/"
icon = "fab fa-linkedin"

[[params.footer.links]]
prefix = "Check out my"
title = "GitHub"
url = "https://github.com/rezarajan"
icon = "fab fa-github"
